# Generated by Django 3.1.1 on 2020-09-12 17:20

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=main.models.upload_path_handler)),
                ('semester', models.IntegerField(choices=[(1, 'SEM 1'), (2, 'SEM 2'), (3, 'SEM 3'), (4, 'SEM 4'), (5, 'SEM 5'), (6, 'SEM 6'), (7, 'SEM 7'), (8, 'SEM 8')])),
                ('branch', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('BIOTECH', 'BIOTECH')], max_length=200)),
            ],
        ),
    ]
